name: story_composer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.2
  ffmpeg_kit_flutter: ^6.0.3
  fvp: ^0.12.0
  path_provider: ^2.1.2
  palette_generator: ^0.3.3+3
  uuid: ^4.2.1
  vector_math: ^2.1.4
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
